// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBki0uYMdKd5jRXv9ga-_uV_KTY6LY2Vcc',
    appId: '1:700412208028:android:66fe1bb5c04a8f5c97de59',
    messagingSenderId: '700412208028',
    projectId: 'safechain-4daf7',
    storageBucket: 'safechain-4daf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEh81DH-7cvCC8noUopNN4YZBpIxoYkUs',
    appId: '1:700412208028:ios:8219a006de3fbc1797de59',
    messagingSenderId: '700412208028',
    projectId: 'safechain-4daf7',
    storageBucket: 'safechain-4daf7.firebasestorage.app',
    iosBundleId: 'com.safechain.safechain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0p1IRdRt4y5nDA-DrQLM6oJEbdngP6oM',
    appId: '1:700412208028:web:de4766292b23cabc97de59',
    messagingSenderId: '700412208028',
    projectId: 'safechain-4daf7',
    authDomain: 'safechain-4daf7.firebaseapp.com',
    storageBucket: 'safechain-4daf7.firebasestorage.app',
    measurementId: 'G-782WJMHBKR',
  );

}